// test sdgf sdn gl sdljkm
export const PROFILE_CATEGORY_OPTIONS = [
  "Design",
  "Technology",
  "Media",
  "Illustration",
  "Marketing",
  "Photography",
  "Writing",
  "Fashion",
  "Beauty",
  "Fitness",
  "Food & Beverage",
  "Travel",
  "Music",
  "Gaming",
  "Finance",
  "Education",
  "Real Estate",
  "Health & Wellness",
  "Non-profit",
  "Other",
] as const;
